version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 20
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 20
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      - dependency-name: "next"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "pa11y-ci"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "pa11y"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: "docker"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      docker-backend:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      docker-frontend:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
