framework:
  cache:
    app: cache.adapter.filesystem
    default_redis_provider: "%env(REDIS_URL)%"
    pools:
      lexik_jwt_blocklist.cache:
        adapter: cache.adapter.redis
      rate_limiter:
        adapter: cache.adapter.redis
