<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260703183000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create app settings table and insert default values';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, default_address VARCHAR(255) NOT NULL, default_price DOUBLE PRECISION NOT NULL, default_max_places INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql("INSERT INTO app_setting (default_address, default_price, default_max_places, created_at, updated_at) VALUES ('Terrain principal', 10, 24, NOW(), NOW())");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE app_setting');
    }
}
