<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709082308 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_present BOOLEAN DEFAULT false NOT NULL, game_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C7893C9E48FD905 ON game_registration (game_id)');
        $this->addSql('CREATE INDEX IDX_8C7893C9A76ED395 ON game_registration (user_id)');
        $this->addSql('ALTER TABLE game_registration ADD CONSTRAINT FK_8C7893C9E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_registration ADD CONSTRAINT FK_8C7893C9A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users DROP age');
        $this->addSql('ALTER TABLE users DROP emergency_contact');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_registration DROP CONSTRAINT FK_8C7893C9E48FD905');
        $this->addSql('ALTER TABLE game_registration DROP CONSTRAINT FK_8C7893C9A76ED395');
        $this->addSql('DROP TABLE game_registration');
        $this->addSql('ALTER TABLE users ADD age INT NOT NULL');
        $this->addSql('ALTER TABLE users ADD emergency_contact VARCHAR(255) DEFAULT NULL');
    }
}
