<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260828113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store administrator-created accounts until email confirmation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pending_user_invitations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, user_data JSON NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PENDING_USER_INVITATION_EMAIL ON pending_user_invitations (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PENDING_USER_INVITATION_TOKEN_HASH ON pending_user_invitations (token_hash)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pending_user_invitations');
    }
}
