<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260828100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add email verification state and tokens';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD email_verified BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('CREATE TABLE email_verification_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EMAIL_VERIFICATION_TOKEN_HASH ON email_verification_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_EMAIL_VERIFICATION_USER ON email_verification_tokens (user_id)');
        $this->addSql('ALTER TABLE email_verification_tokens ADD CONSTRAINT FK_EMAIL_VERIFICATION_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE email_verification_tokens');
        $this->addSql('ALTER TABLE users DROP email_verified');
    }
}