name: CI

on:
  push:
    branches:
      - "**"

jobs:
  frontend:
    uses: ./.github/workflows/frontend-ci.yml
    with:
      node-version: 20
      working-directory: frontend

  backend:
    uses: ./.github/workflows/backend-ci.yml
    with:
      php-version: 8.4
      working-directory: backend

  scanner:
    needs: [frontend, backend]
    uses: ./.github/workflows/security-scanner.yml

  lighthouse:
    needs: [scanner]
    uses: ./.github/workflows/lighthouse.yml

  pa11y:
    needs: [lighthouse]
    uses: ./.github/workflows/pa11y.yml

  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [frontend, backend, lighthouse, scanner, pa11y]
    uses: ./.github/workflows/release.yml
    with:
      node-version: 20
    secrets:
      RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

  deploy-prod:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [frontend, backend, scanner, lighthouse, pa11y, release]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
