name: Semgrep Security Scan

on:
  workflow_call:

jobs:
  security-scanner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/security-audit \
            --config p/owasp-top-ten \
            --config p/secrets \
            --config p/php \
            --config p/javascript \
            --config p/typescript \
            --config p/react \
            --config p/nodejs \
            --config p/nextjs
